---
- name: Copy certs from source server to temp ansible directory
  fetch:
    src: "{{ source_server_cert_working_dir }}/{{ item }}"
    dest: "~/"
    flat: true
  when: inventory_hostname == source_server
  with_items:
    - "{{ source_server_cacert_name }}" 
    - "{{ source_server_cert_name }}"
    - "{{ source_server_key_name }}"

- name: Copy cacert from temp ansible directory to target
  copy:
    src: "~/{{ source_server_cacert_name }}"
    dest: "{{ target_server_cert_working_dir }}/{{ target_server_cacert_name }}"
  when: inventory_hostname != source_server

- name: Copy cert from temp ansible directory to target
  copy:
    src: "~/{{ source_server_cert_name }}"
    dest: "{{ target_server_cert_working_dir }}/{{ target_server_cert_name }}"
  when: inventory_hostname != source_server

- name: Copy key from temp ansible directory to target
  copy:
    src: "~/{{ source_server_key_name }}"
    dest: "{{ target_server_cert_working_dir }}/{{ target_server_key_name }}"
  when: inventory_hostname != source_server
